### PR TITLE
Fixes an alignment problem in the backend at the module settings

### PR DESCRIPTION
**Pull request by OMOSde**

### CODE REVIEW

**Comment by qzminski** [comment]
Before I merge this one, what's the problem exactly? Right now I have the following backend view and there is no need to fix anything here:

2018-08-30 at 16 41

Any particular Contao version you are refering to?

**Comment by OMOSde** [comment]
I use a Contao 4.4.23 on a Chrome Version 68.0.3440.106. I tested on Opera too. Same result. The alignment is correct in Firefox and Edge.

codefog_instagram_dca_problem

**Comment by fritzmg** [comment]
This should have been fixed in Contao 4.4.15. See https://github.com/contao/core-bundle/issues/1287

**Comment by qzminski** [comment]
@OMOSde can you please check what @fritzmg has suggested?

**Pull request closed without merging**
